- name: Run Scraper
        run: python fetch_epg.py

      - name: Commit and Push
        run: |
          git config --global user.name "EPG-Bot"
          git config --global user.email "bot@github.com"
          git add epg.xml epg.xml.gz tvg-ids.txt
          git commit -m "Update EPG files (xml & gz)" || exit 0
          git push
